# Generated by Django 3.2.14 on 2022-07-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20220709_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='img_url',
        ),
        migrations.AddField(
            model_name='location',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='places.image', verbose_name='Картинка места'),
        ),
    ]
