# Generated by Django 3.2.14 on 2022-07-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='placeId',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
