# Generated by Django 3.2.14 on 2022-07-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_rename_placeid_location_placeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='title_short',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
